
image:
  file: .gitpod/Dockerfile

ports:
  - port: 8080
    onOpen: open-browser

tasks:
  - init: yarn install
  - name: Kafka
    init: chmod +x deployment/scripts/*.bash && ./deployment/scripts/setup.bash 
    command: > 
      KAFKA_HOME=/kafka &&
      ./deployment/scripts/init-kafka.bash $KAFKA_HOME .env
  - name: Nginx
    command: export NGINX_DOCROOT="${GITPOD_REPO_ROOT}/www" && nginx
  - name: mongodb
    command: mkdir -p /workspace/data/mongo && mongod --dbpath /workspace/data/mongo
  - name: redis
    command:  redis-server 
  - name: minio
    command: >
      mkdir -p /workspace/data/minio &&
      export MINIO_ROOT_USER=access_key MINIO_ROOT_PASSWORD=secret_access_key &&
      /minio/minio server /workspace/data/minio --console-address ":9001"


vscode:
  extensions:
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
